server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodiehub
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics